language: generic

sudo: required

services:
  - docker

env:
  - REPO=pyinstaller-alpine

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - bash build-all.sh

branches:
  only:
    - master
